mod correlation;
mod delay;
mod mean;
mod minmax;
mod quantile;
mod rank;
mod returns;
mod skew;
mod stdev;
mod sum;

pub use correlation::Correlation;
pub use delay::Delay;
pub use mean::Mean;
pub use minmax::{ArgMax, ArgMin, Max, Min};
pub use quantile::Quantile;
pub use rank::Rank;
pub use returns::LogReturn;
pub use skew::Skew;
pub use stdev::Stdev;
pub use sum::Sum;
