name: ci

on: 
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

jobs:
  rust:
    runs-on: ubuntu-latest
    container: ubuntu
    steps:
      - uses: actions/checkout@v2

      - name: Install tools
        run: |
          apt-get update
          apt-get install -y curl build-essential pkg-config libssl-dev git
        env:
          DEBIAN_FRONTEND: noninteractive

      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: nightly
          components: rustfmt

      - name: Install python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          architecture: x64

      - name: Check which Python we use
        run: |
          echo $(which python)
          ls $(dirname $(which python))

      - name: Install other dependent tools
        run: |
          python -m pip install poetry
          cargo install just

      - name: Install python dependencies
        run: just bootstrap-python

      - name: Is the code formatted?
        run: |
          cargo fmt --all --manifest-path native/Cargo.toml -- --check -q

      - name: Run tests
        run: just test
